export const CANVAS_W = 640;
export const CANVAS_H = 360;
export const GROUND_Y = 300;
export const GRAVITY = 0.65;
export const ROUND_TIME = 75;

export const BOSSES = [
  {
    id: 1,
    name: "MICHAEL TRUELL",
    shortName: "TRUELL",
    title: "CURSOR CEO",
    faceKey: "truell",
    themeKey: "cursor",
    company: "CURSOR",
    hp: 100,
    arena: "CURSOR HQ",
    location: "San Francisco",
    skin: "#e8c4a0",
    hair: "#3d2914",
    suit: "#1e3a5f",
    accent: "#3b82f6",
    tie: "#60a5fa",
    features: { glasses: true, youthful: true },
    ai: { aggression: 0.6, speed: 2.6, power: 10 },
    staff: ["Ben Lang", "Sunita Rao", "Eric Zakariasson", "Ivana O", "Jen Kha"],
    special: { name: "TAB BLADE", color: "#3b82f6", damage: 12, speed: 6, cooldown: 3.0, gap: "high" },
    quote: "Tab-complete THIS, Truell!",
  },
  {
    id: 2,
    name: "ELON MUSK",
    shortName: "MUSK",
    title: "XAI FOUNDER",
    faceKey: "musk",
    themeKey: "xai",
    company: "xAI",
    hp: 110,
    arena: "XAI / TESLA HQ",
    location: "Austin, TX",
    skin: "#d4a88c",
    hair: "#2d2d2d",
    suit: "#111827",
    accent: "#dc2626",
    tie: "#ef4444",
    features: { smirk: true, broad: true },
    ai: { aggression: 0.78, speed: 3.0, power: 12 },
    staff: ["Grok Team", "Rocket Eng", "Megapack", "Optimus", "Cybertruck"],
    special: { name: "ROCKET", color: "#ef4444", damage: 15, speed: 7, cooldown: 2.6, gap: "low" },
    quote: "Your AI can't autocomplete a comeback.",
  },
  {
    id: 3,
    name: "SAM ALTMAN",
    shortName: "ALTMAN",
    title: "OPENAI CEO",
    faceKey: "altman",
    themeKey: "openai",
    company: "OpenAI",
    hp: 120,
    arena: "OPENAI HQ",
    location: "San Francisco",
    skin: "#ddb896",
    hair: "#8b7355",
    suit: "#312e81",
    accent: "#8b5cf6",
    tie: "#a78bfa",
    features: { baldish: true, lean: false },
    ai: { aggression: 0.72, speed: 2.9, power: 13 },
    staff: ["GPT Team", "Sora Crew", "Safety", "DevRel", "Researchers"],
    special: { name: "GPT ORB", color: "#a78bfa", damage: 16, speed: 6.5, cooldown: 2.4, gap: "high" },
    quote: "Not so open now, are you?",
  },
  {
    id: 4,
    name: "DARIO AMODEI",
    shortName: "AMODEI",
    title: "ANTHROPIC CEO",
    faceKey: "amodei",
    themeKey: "anthropic",
    company: "ANTHROPIC",
    hp: 130,
    arena: "ANTHROPIC HQ",
    location: "San Francisco",
    skin: "#e0b890",
    hair: "#5c4033",
    suit: "#7c2d12",
    accent: "#ea580c",
    tie: "#f97316",
    features: { intense: true, jacked: true },
    ai: { aggression: 0.85, speed: 3.1, power: 14 },
    staff: ["Claude Team", "Alignment", "Interpretability", "Frontier Red", "RSP Crew"],
    special: { name: "CLAUDE BEAM", color: "#f97316", damage: 18, speed: 7.5, cooldown: 2.2, gap: "low" },
    quote: "Constitutionally... you LOSE.",
  },
];

export const ARENA_THEMES = {
  cursor: { wall: "#0f172a", floor: "#1e293b", neon: "#3b82f6", glass: "#60a5fa", screen: "#1d4ed8" },
  xai: { wall: "#0c0a09", floor: "#1c1917", neon: "#dc2626", glass: "#f87171", screen: "#991b1b" },
  deepmind: { wall: "#042f2e", floor: "#134e4a", neon: "#10b981", glass: "#6ee7b7", screen: "#047857" },
  openai: { wall: "#1e1b4b", floor: "#312e81", neon: "#8b5cf6", glass: "#c4b5fd", screen: "#6d28d9" },
  anthropic: { wall: "#431407", floor: "#7c2d12", neon: "#ea580c", glass: "#fdba74", screen: "#c2410c" },
};

export const CONTROLS = {
  left: ["ArrowLeft", "a", "A"],
  right: ["ArrowRight", "d", "D"],
  up: ["ArrowUp", "w", "W"],
  down: ["ArrowDown", "s", "S"],
  punch: ["z", "Z"],
  kick: ["x", "X"],
  special: ["c", "C"],
  start: ["Enter", " "],
};
